name: Raise Question
description: File a question
title: "[Q]: "
labels: ["question", "triage"]
assignees:
  - octocat
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see!
      value: "The error shows up ..."
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: Expected result?
      placeholder: Tell us what you see!
      value: "I expect ..."
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
  - type: input	
    id: browser-version	
    attributes:	
      label: Browser version
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output if any
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

    
